sonar.projectKey=jazambrano21_Sistema-de-Parqueadero
sonar.projectName=ms-zonas-espacios
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes
sonar.exclusions=**/target/**,**/*.md
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
