spring:
  application:
    name: zonas-espacios
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3308/parkin_bd}
    username: ${DB_USERNAME:parkin_user}
    password: ${DB_PASSWORD:parkin_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  sql:
    init:
      mode: never

server:
  port: 8081
