spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/usuarios_db
        username: postgrest
        password: qwerty12
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            format_sql: true

    sql:
        init:
            mode: always

    security:
        oauth2:
            resourceserver:
                jwt:
                    jwk-set-uri: http://localhost:9000/oauth2/jwks

# URL del servidor OAuth para solicitar tokens firmados
oauth:
    server:
        url: http://localhost:9000
